# site settings
title: Solar Pi
subtitle: 
email: TeamSolarPi@gmail.com
description: The website for the Solar Pi project
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
author:
street_address: No, you're not going to my house for a visit
city: No, you're not having the name of the city I take residence in
state: We don't have states in my country
zip_code: We don't have zip codes in my country...
country: The Internet is borderless :P
phone: We don't have one, actually

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/SolarPi
gitlab_url: 
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
